# options for analysis running
run:
  timeout: 2m
  skip-files:
    - "zz_generated.*"
linters:
  enable:
    - revive
    - whitespace
    - wsl
    - goimports
    - nolintlint
    - predeclared
    - unconvert
    - gocritic
    - godot
    - gofumpt
    - misspell
linters-settings:
  goimports:
    local-prefixes: github.com/gardener/gardenctl-v2
