#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

if [[ -z "${MAIN_REPO_DIR}" ]]; then
  export MAIN_REPO_DIR="$(readlink -f $(dirname ${0})/..)"
else
  export MAIN_REPO_DIR="$(readlink -f "${MAIN_REPO_DIR}")"
fi

if [[ -z "${LD_FLAGS}" ]]; then
  export LD_FLAGS=$("${MAIN_REPO_DIR}"/hack/get-build-ld-flags.sh)
fi

###############################################################################

"${MAIN_REPO_DIR}"/hack/build-linux-amd64.sh
"${MAIN_REPO_DIR}"/hack/build-linux-arm64.sh
"${MAIN_REPO_DIR}"/hack/build-darwin-amd64.sh
"${MAIN_REPO_DIR}"/hack/build-darwin-arm64.sh
"${MAIN_REPO_DIR}"/hack/build-windows-amd64.sh

