#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o pipefail

if [ -z "$SOURCE_PATH" ]; then
  SOURCE_PATH="$(dirname "$0")/.."
fi
export SOURCE_PATH="$(readlink -f "$SOURCE_PATH")"

pushd "${SOURCE_PATH}" > /dev/null

if [[ -z "$(git config --global user.email)" ]]; then
  echo "Setting global Git user.email to gardener@sap.com"
  git config --global user.email "gardener@sap.com"
else
  echo "Global Git user.email is already set to $(git config --global user.email)"
fi

if [[ -z "$(git config --global user.name)" ]]; then
  echo "Setting global Git user.name to Gardener CI/CD"
  git config --global user.name "Gardener CI/CD"
else
  echo "Global Git user.name is already set to $(git config --global user.name)"
fi

export GO_TEST_RACE=1
export GOLANGCI_LINT_VERBOSE=1
export GOLANGCI_LINT_TIMEOUT=5m

if [ "${TEST_COV+yes}" = yes ] ; then
  # supposed to be run in release jobs
  make verify-extended
else
  # run test instead of test-cov to speed-up jobs, as coverage slows down tests significantly
  make check-generate verify
fi

popd > /dev/null
