#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o pipefail

# For the check step concourse will set the following environment variables:
# MAIN_REPO_DIR - path to the main repository

if [[ -z "${MAIN_REPO_DIR}" ]]; then
  export MAIN_REPO_DIR="$(readlink -f "$(dirname ${0})/..")"
else
  export MAIN_REPO_DIR="$(readlink -f ${MAIN_REPO_DIR})"
fi

pushd "${MAIN_REPO_DIR}" > /dev/null

if [[ -z "$(git config --global user.email)" ]]; then
  echo "Setting global Git user.email to gardener@sap.com"
  git config --global user.email "gardener@sap.com"
else
  echo "Global Git user.email is already set to $(git config --global user.email)"
fi

if [[ -z "$(git config --global user.name)" ]]; then
  echo "Setting global Git user.name to Gardener CI/CD"
  git config --global user.name "Gardener CI/CD"
else
  echo "Global Git user.name is already set to $(git config --global user.name)"
fi

export GOLANGCI_LINT_ADDITIONAL_FLAGS="--verbose --timeout 2m"
export GO_TEST_ADDITIONAL_FLAGS="-race"

if [ "${TEST_COV+yes}" = yes ] ; then
  # supposed to be run in release jobs
  make verify-extended
else
  # run test instead of test-cov to speed-up jobs, as coverage slows down tests significantly
  make check-generate verify
fi

popd > /dev/null
