name: Prepare Release

inputs:
  effective-version:
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: write-latest-version
      shell: bash
      env:
        EFFECTIVE_VERSION: ${{ inputs.effective-version }}
      run: |
        set -euo pipefail
        echo "${EFFECTIVE_VERSION}" > LATEST
